#!/usr/bin/env python3
"""Generate a generic medial-congruent tibial articular surface as a binary STL.

NOT A MEDICAL DEVICE, AND NOT A REPRODUCTION OF ANY PRODUCT. This is a generic
research/teaching shape: the bearing counterpart of the generic size-8 TKA
femoral component built by `generate_femoral_component_stl.py`, whose geometry
reaches this generator through `femoral_geometry.py` -- imported from that
generator, not restated, so the two cannot drift apart. Do not use it for
clinical planning, implantation, or any purpose requiring a validated articular
surface.

WHAT MAKES IT CONFORM
---------------------
The articular surface is not fitted to the femoral component by eye, and it is
not an idealised sphere that happens to be about the right size. It is carved
*by* the femoral component: the femoral articular envelope is subtracted from a
bearing blank, so every point of both dishes is generated by the femoral
surface itself -- including its coronal fall-off and its condylar edge roll,
which no radius fit would reproduce.

The two compartments differ only in how the femoral component is moved while
it carves:

  medial   Swept about the centre of curvature of its own distal condyle
           (R = 39.24 mm at size 8), which is a rotation, not a translation.
           The envelope is therefore barely larger than the envelope at
           extension: a deep, congruent socket that constrains anterior-
           posterior translation. Sound by construction, because no point of
           the J-curve lies further from that centre than the distal radius
           itself (--report prints the margin), so the flexed component can
           never reach below the socket the extension pose carves.

  lateral  The same envelope, translated through a posterior excursion before
           being subtracted. Sweeping a translation instead of a rotation
           leaves the coronal profile untouched but flattens the sagittal one
           over the length of the excursion: coronally conforming, sagittally
           relieved, free to roll back. This is what makes the bearing medial
           congruent rather than simply congruent.

Both compartments are then re-checked against a full flexion sweep, and the
result is reported as a minimum gap that has to be non-negative.

Usage:
    python3 tools/generate_articular_surface_stl.py --thickness 10
    python3 tools/generate_articular_surface_stl.py --side left --thickness 12
"""

from __future__ import annotations

import argparse
from pathlib import Path
from types import SimpleNamespace

import numpy as np

import femoral_geometry as F
from sdf_mesh import (check_watertight, polygon_sdf, polygonise,
                      write_binary_stl)

FEMORAL_SIZE = 8

# --- Bearing envelope: design assumptions, none of this is published ---------
INSERT_ML = 70.0             # overall medial-lateral width
INSERT_AP = 48.0             # overall anterior-posterior depth
POST_WIDENING = 0.04         # plateau is this fraction wider posteriorly
OUTLINE_EXPONENT = 2.6       # superellipse exponent of the plateau outline
Y_DISH = -1.0                # A/P position of the medial socket floor
CLEARANCE = 0.4              # bearing gap; also the print fit at the socket

# Lateral relief. The femoral envelope is translated over this A/P excursion
# before it carves the lateral compartment, which is what drops that side's
# sagittal conformity and lets the lateral condyle roll back.
LATERAL_TRAVEL_ANT = 4.0     # anterior of the extension contact
LATERAL_TRAVEL_POST = 8.0    # posterior of it
LATERAL_STEPS = 25
# Where the lateral relief stops. Inside the intercondylar notch there is no
# femoral material to carve with, so splitting here leaves the eminence to be
# shaped by the medial sweep and by the wall ceiling.
X_SPLIT = -6.0
SPLIT_BLEND = 3.0

# Peripheral wall heights above the articular floor. The medial wall is tall --
# a congruent socket is an A/P constraint, and its anterior lip is what resists
# anterior femoral translation. The posterolateral wall is low, so the lateral
# condyle can roll back over it.
WALL_MED_ANT = 7.0
WALL_MED_POST = 6.0
WALL_LAT_ANT = 5.0
WALL_LAT_POST = 3.0
# Intercondylar eminence. The femoral component's notch is a through-cut, so
# the carve leaves the whole central band standing at blank height; this is
# what shapes what is left into a ridge rather than a full-length mesa.
EMINENCE_HEIGHT = 4.5        # above the articular floor, at its peak
EMINENCE_Y = 0.0             # A/P position of the peak
EMINENCE_SIGMA = 13.0        # A/P fall-off
EMINENCE_HALFWIDTH = 9.0
EMINENCE_BLEND = 6.0
EMINENCE_MARGIN = 4.0        # eminence trim stops this far from the A/P margin
EMINENCE_MARGIN_BLEND = 8.0
WALL_FILLET = 1.5            # blend from the articular surface into the wall
RIM_BREAK = 1.0              # break on the top edge of the wall
BASE_CHAMFER = 0.8           # chamfer on the inferior edge

# --- Sweep: the kinematics the medial socket is carved by --------------------
FLEXION_MIN = -5.0           # hyperextension, degrees
FLEXION_MAX = 120.0
FLEXION_STEP = 2.0
AXIAL_ROTATION = 15.0        # tibial internal rotation at full flexion, degrees
AXIAL_SATURATION = 0.60      # reached by this fraction of the flexion range


def smoothstep(t):
    t = np.clip(t, 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def rounded_intersection(a, b, r):
    a, b = a + r, b + r
    return (np.minimum(np.maximum(a, b), 0.0)
            + np.hypot(np.maximum(a, 0.0), np.maximum(b, 0.0)) - r)


def smooth_min(a, b, k):
    h = np.clip(0.5 + 0.5 * (b - a) / k, 0.0, 1.0)
    return b * (1 - h) + a * h - k * h * (1 - h)


def geometry(thickness: float, clearance: float) -> SimpleNamespace:
    """Bearing frame: +x medial, +y posterior, +z proximal, z = 0 on the tray.

    The femoral component is seated in full extension with its distal-most
    articular point one clearance above the socket floor, and the sweep pivots
    about the centre of curvature of that distal condyle.
    """
    f = F.geometry(FEMORAL_SIZE)
    y_contact, z_contact, radius = F.distal_contact(f)

    g = SimpleNamespace(
        femoral=f,
        thickness=thickness,
        clearance=clearance,
        half_ml=INSERT_ML / 2.0,
        half_ap=INSERT_AP / 2.0,
        radius=radius,
        # Centre line of one femoral condyle: midway between the edge of the
        # intercondylar notch and the M/L edge of the component at the contact.
        x_cond=0.5 * (f.notch_hw + F.half_width(y_contact, z_contact, f)),
    )
    g.pivot_f = np.array([g.x_cond, y_contact, z_contact + radius])
    g.pivot_i = np.array([g.x_cond, Y_DISH, thickness + clearance + radius])
    g.contact_i = np.array([g.x_cond, Y_DISH, thickness + clearance])
    return g


def poses(g: SimpleNamespace, step: float = FLEXION_STEP):
    """(flexion, axial rotation) pairs, both in radians.

    Axial rotation is negative because the bearing frame puts the congruent
    compartment on +x: rotating the femoral component negatively about the
    vertical axis through the medial pivot carries the *lateral* condyle
    posteriorly, which is the rollback a medial-pivot knee produces.
    """
    theta = np.radians(np.arange(FLEXION_MIN, FLEXION_MAX + 0.5 * step, step))
    span = np.radians(FLEXION_MAX) * AXIAL_SATURATION
    psi = -np.radians(AXIAL_ROTATION) * smoothstep(theta / span)
    return list(zip(theta, psi))


def to_femoral(g, x, y, z, theta, psi, dy=0.0):
    """Map bearing-frame coordinates into the femoral component's frame.

    `dy` shifts the component posteriorly in the bearing frame before the
    rotation is undone; it is what generates the lateral compartment's relief.
    """
    qx = x - g.pivot_i[0]
    qy = (y - dy) - g.pivot_i[1]
    qz = z - g.pivot_i[2]

    c, s = np.cos(psi), np.sin(psi)
    ax = qx * c + qy * s
    ay = -qx * s + qy * c

    c, s = np.cos(theta), np.sin(theta)
    fy = ay * c - qz * s
    fz = ay * s + qz * c

    return ax + g.pivot_f[0], fy + g.pivot_f[1], fz + g.pivot_f[2]


def to_bearing(g, x, y, z, theta, psi):
    """Map femoral-frame coordinates into the bearing frame."""
    qx = x - g.pivot_f[0]
    qy = y - g.pivot_f[1]
    qz = z - g.pivot_f[2]

    c, s = np.cos(theta), np.sin(theta)
    ay = qy * c + qz * s
    az = -qy * s + qz * c

    c, s = np.cos(psi), np.sin(psi)
    return (qx * c - ay * s + g.pivot_i[0],
            qx * s + ay * c + g.pivot_i[1],
            az + g.pivot_i[2])


def outline_polygon(g: SimpleNamespace, n: int = 512) -> np.ndarray:
    """Tibial plateau outline: a superellipse, slightly wider posteriorly.

    Closed all the way round, with no posterior cruciate cut-out: a congruent
    medial socket is itself the A/P restraint, so this bearing is designed for
    a knee with the posterior cruciate sacrificed and the posterior margin runs
    continuously behind the intercondylar eminence.
    """
    t = np.linspace(0.0, 2.0 * np.pi, n, endpoint=False)
    k = 2.0 / OUTLINE_EXPONENT
    x = g.half_ml * np.sign(np.cos(t)) * np.abs(np.cos(t)) ** k
    y = g.half_ap * np.sign(np.sin(t)) * np.abs(np.sin(t)) ** k
    x = x * (1.0 + POST_WIDENING * y / g.half_ap)
    return np.stack([x, y], axis=1)


def wall_ceiling(g, x, y):
    """Height the bearing is allowed to reach: the peripheral wall profile.

    Capping the blank can only remove material, so it can never introduce
    interference with the femoral component. It stops the walls and the
    intercondylar eminence -- which the carve leaves standing at full blank
    height, the femoral component never having reached them -- from being
    taller than a bearing's should be.
    """
    med = smoothstep((x / g.x_cond + 1.0) / 2.0)     # 0 lateral -> 1 medial
    post = smoothstep((y / g.half_ap + 1.0) / 2.0)   # 0 anterior -> 1 posterior
    ant = WALL_LAT_ANT + (WALL_MED_ANT - WALL_LAT_ANT) * med
    back = WALL_LAT_POST + (WALL_MED_POST - WALL_LAT_POST) * med
    wall = ant + (back - ant) * post

    # Trim the central band down to a ridge, but let go of it towards the A/P
    # margins so the anterior and posterior walls stay continuous across the
    # full width instead of being notched out at the midline.
    central = 1.0 - smoothstep(
        (np.abs(x) - EMINENCE_HALFWIDTH) / EMINENCE_BLEND)
    central = central * smoothstep(
        (g.half_ap - EMINENCE_MARGIN - np.abs(y)) / EMINENCE_MARGIN_BLEND)
    ridge = EMINENCE_HEIGHT * np.exp(-((y - EMINENCE_Y) / EMINENCE_SIGMA) ** 2)
    return g.thickness + wall + np.minimum(ridge - wall, 0.0) * central


def build_volume(g: SimpleNamespace, resolution: float, field: F.ArticularField):
    outline = outline_polygon(g)
    margin = 2.0
    z_top = g.thickness + max(WALL_MED_ANT, WALL_MED_POST,
                              WALL_LAT_ANT, WALL_LAT_POST)

    xs = np.arange(-(g.half_ml + margin), g.half_ml + margin + resolution,
                   resolution, dtype=np.float64)
    ys = np.arange(-(g.half_ap + margin), g.half_ap + margin + resolution,
                   resolution, dtype=np.float64)
    zs = np.arange(-margin, z_top + margin + resolution,
                   resolution, dtype=np.float64)

    # The footprint and the wall ceiling depend only on (x, y).
    xx, yy = np.meshgrid(xs, ys, indexing="ij")
    d_foot = polygon_sdf(xx, yy, outline)
    ceiling = wall_ceiling(g, xx, yy)

    sweep = poses(g)
    travel = np.linspace(-LATERAL_TRAVEL_ANT, LATERAL_TRAVEL_POST, LATERAL_STEPS)

    vol = np.empty((len(xs), len(ys), len(zs)), dtype=np.float32)
    for i0 in range(0, len(xs), 32):
        sl = slice(i0, i0 + 32)
        x = xs[sl][:, None, None]
        y = ys[None, :, None]
        z = zs[None, None, :]

        # Blank: the plateau footprint, from the tray up to the wall ceiling.
        d = rounded_intersection(d_foot[sl][:, :, None], -z, BASE_CHAMFER)
        d = rounded_intersection(d, z - ceiling[sl][:, :, None], RIM_BREAK)

        # Medial: the femoral envelope swept about its own distal centre of
        # curvature. A rotation about that centre barely enlarges the envelope,
        # so what this carves is a congruent socket.
        carve = np.full(np.broadcast_shapes(x.shape, y.shape, z.shape),
                        np.inf, dtype=np.float32)
        for theta, psi in sweep:
            np.minimum(carve, field(*to_femoral(g, x, y, z, theta, psi)),
                       out=carve, casting="unsafe")

        # Lateral: the same envelope in extension, translated through the
        # rollback excursion. Restricted to the lateral side of the split, so
        # the socket and the eminence keep the shape the medial sweep gave them.
        relief = np.full(carve.shape, np.inf, dtype=np.float32)
        for dy in travel:
            np.minimum(relief, field(*to_femoral(g, x, y, z, 0.0, 0.0, dy)),
                       out=relief, casting="unsafe")
        relief = np.maximum(relief, x - X_SPLIT)
        carve = smooth_min(carve, relief, SPLIT_BLEND)

        # A running fit rather than line-to-line contact, and a guarantee that
        # nothing is ever carved below the nominal thickness. The medial sweep
        # is already tangent to that plane, so the clamp only holds the floor.
        carve -= g.clearance
        carve = np.maximum(carve, g.thickness - z)
        vol[sl] = rounded_intersection(d, -carve, WALL_FILLET)

    return vol, xs, ys, zs


# --- Measurement -------------------------------------------------------------

def top_surface(vol, zs):
    """Height of the bearing's upper surface over each (x, y) column.

    Scanning a column upwards, the last sample inside the solid is the top
    face: the articular surface over the dishes, the crest over the walls.
    Reading it out of the sampled field rather than off the mesh is what keeps
    the underside and the outer wall faces from being mistaken for it.
    """
    inside = vol <= 0
    hit = inside.any(axis=2)
    last = inside.shape[2] - 1 - np.argmax(inside[:, :, ::-1], axis=2)
    last = np.clip(last, 0, inside.shape[2] - 2)
    i, j = np.indices(last.shape)
    v0, v1 = vol[i, j, last], vol[i, j, last + 1]
    t = np.where(v1 > v0, v0 / (v0 - v1), 0.0)
    return np.where(hit, zs[last] + (zs[1] - zs[0]) * np.clip(t, 0.0, 1.0),
                    np.nan)


def _fit_circle(u, v):
    """Least-squares circle through (u, v); returns the radius, or None."""
    ok = np.isfinite(u) & np.isfinite(v)
    u, v = np.asarray(u)[ok], np.asarray(v)[ok]
    if len(u) < 5:
        return None
    a = np.stack([u, v, np.ones_like(u)], axis=1)
    sol, *_ = np.linalg.lstsq(a, u ** 2 + v ** 2, rcond=None)
    uc, vc = sol[0] / 2.0, sol[1] / 2.0
    r2 = sol[2] + uc ** 2 + vc ** 2
    return float(np.sqrt(r2)) if r2 > 0 else None


def dish_floor(xs, ys, h, x0, band=8.0):
    """Lowest point of one compartment's articular surface."""
    m = np.abs(xs - x0) < band
    sub = h[m]
    i, j = np.unravel_index(int(np.nanargmin(sub)), sub.shape)
    return float(ys[j]), float(sub[i, j])


def sagittal_radius(xs, ys, h, x0, y0, span=10.0):
    i = int(np.argmin(np.abs(xs - x0)))
    m = np.abs(ys - y0) < span
    return _fit_circle(ys[m], h[i][m])


def coronal_radius(xs, ys, h, x0, y0, span=9.0):
    j = int(np.argmin(np.abs(ys - y0)))
    m = np.abs(xs - x0) < span
    return _fit_circle(xs[m], h[:, j][m])


def wall_crest(xs, ys, h, x0, y_lo, y_hi, floor, band=10.0):
    """Highest point of the bearing over an (x, y) window, above a dish floor."""
    mx = np.abs(xs - x0) < band
    my = (ys > y_lo) & (ys < y_hi)
    win = h[np.ix_(mx, my)]
    if not np.isfinite(win).any():
        return float("nan")
    return float(np.nanmax(win) - floor)


def dish_rise(xs, ys, h, x0, y0, offset):
    """How far the articular surface climbs `offset` mm behind the dish floor."""
    i = int(np.argmin(np.abs(xs - x0)))
    j = int(np.argmin(np.abs(ys - (y0 + offset))))
    return float(h[i, j] - h[i, int(np.argmin(np.abs(ys - y0)))])


def flat_length(xs, ys, h, x0, y0, tol=0.25):
    """A/P run over which the articular surface stays within `tol` of its floor.

    A fitted radius says little about a compartment that has been relieved by a
    translation -- the floor is genuinely flat there, not gently curved -- so
    this is the number that separates the two compartments honestly.
    """
    i = int(np.argmin(np.abs(xs - x0)))
    j = int(np.argmin(np.abs(ys - y0)))
    floor, col = h[i, j], h[i]
    lo = hi = j
    while lo > 0 and np.isfinite(col[lo - 1]) and col[lo - 1] - floor <= tol:
        lo -= 1
    while hi < len(ys) - 1 and np.isfinite(col[hi + 1]) and col[hi + 1] - floor <= tol:
        hi += 1
    return float(ys[hi] - ys[lo])


def verify_clearance(g, verts, field, step=1.0):
    """Sweep the femoral component again and check it never cuts the bearing.

    Interference between two solids implies at least one surface vertex of one
    lies inside the other, so the minimum of the femoral field over the
    bearing's vertices is a sound interference test -- and where the two come
    closest it is the gap between them.
    """
    worst, worst_at = np.inf, None
    for theta, psi in poses(g, step):
        d = float(field(*to_femoral(g, verts[:, 0], verts[:, 1], verts[:, 2],
                                    theta, psi)).min())
        if d < worst:
            worst, worst_at = d, np.degrees(theta)
    return worst, worst_at


def condyle_track(g, x_cond, limit_deg, step=2.0):
    """A/P travel of a condyle's contact point, over the tracked flexion range.

    The contact point is wherever that condyle's sagittal J-curve reaches
    lowest in the bearing frame, so it is a different *material* point at every
    angle -- which is the point: on a pivot it barely moves. Past `limit_deg`
    the femoral component has lifted clear of a fixed pivot (see
    `femoral_geometry.contact_lift`), and where there is no contact there is no
    contact point to track, so the measurement stops there.
    """
    jy, jz, _, _ = F.articular_profile(g.femoral)
    track = []
    for theta, psi in poses(g, step):
        if not 0.0 <= np.degrees(theta) <= limit_deg:
            continue
        _, by, bz = to_bearing(g, np.full_like(jy, x_cond), jy, jz, theta, psi)
        track.append(by[int(np.argmin(bz))])
    return float(min(track)), float(max(track))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--thickness", type=float, default=10.0,
                        help="polyethylene thickness at the medial socket floor")
    parser.add_argument("--side", choices=("right", "left"), default="right")
    parser.add_argument("--clearance", type=float, default=CLEARANCE)
    parser.add_argument("-o", "--out", type=Path, default=None)
    parser.add_argument("-r", "--resolution", type=float, default=0.25)
    args = parser.parse_args()

    g = geometry(args.thickness, args.clearance)
    field = F.ArticularField(g.femoral)
    out = args.out or Path(
        f"models/generic-tka-articular-surface-mc-size{FEMORAL_SIZE}"
        f"-{args.thickness:g}mm-{args.side}.stl")

    vol, xs, ys, zs = build_volume(g, args.resolution, field)
    verts, faces, volume = polygonise(vol, args.resolution,
                                      (xs[0], ys[0], zs[0]))

    h = top_surface(vol, zs)
    my, mz = dish_floor(xs, ys, h, g.x_cond)
    ly, lz = dish_floor(xs, ys, h, -g.x_cond)
    fem_cor = F.coronal_radius(g.femoral, field)
    med_sag = sagittal_radius(xs, ys, h, g.x_cond, my)
    lat_sag = sagittal_radius(xs, ys, h, -g.x_cond, ly)
    med_cor = coronal_radius(xs, ys, h, g.x_cond, my)
    lat_cor = coronal_radius(xs, ys, h, -g.x_cond, ly)
    med_lip = wall_crest(xs, ys, h, g.x_cond, -g.half_ap, my - 6.0, mz)
    lat_wall = wall_crest(xs, ys, h, -g.x_cond, ly + 6.0, g.half_ap, lz)
    eminence = wall_crest(xs, ys, h, 0.0, -12.0, 12.0, mz, band=4.0)
    gap, gap_at = verify_clearance(g, verts, field)
    lift = F.contact_lift(g.femoral, np.arange(0.0, FLEXION_MAX + 1.0))
    tracking = float(np.interp(1.0, lift, np.arange(0.0, FLEXION_MAX + 1.0)))
    mlo, mhi = condyle_track(g, g.x_cond, tracking)
    llo, lhi = condyle_track(g, -g.x_cond, tracking)

    if args.side == "left":
        verts = verts.copy()
        verts[:, 0] *= -1.0
        faces = faces[:, ::-1]

    write_binary_stl(
        out, verts, faces,
        f"Generic medial-congruent TKA articular surface, size {FEMORAL_SIZE} "
        f"{args.thickness:g}mm {args.side} - educational model, not a device",
    )

    lo, hi = verts.min(axis=0), verts.max(axis=0)
    R = g.radius
    ratio = (lambda r: f"{R / r:.2f}" if r else "  n/a")
    print(f"wrote {out}  ({args.side} knee)")
    print(f"  triangles        : {len(faces):,}")
    print(f"  overall M/L      : {hi[0]-lo[0]:.2f} mm")
    print(f"  overall A/P      : {hi[1]-lo[1]:.2f} mm")
    print(f"  overall height   : {hi[2]-lo[2]:.2f} mm")
    print(f"  thickness (floor): {mz:.2f} mm  (nominal {args.thickness:g})")
    print(f"  condyle centres  : +/-{g.x_cond:.2f} mm from the midline")
    print()
    print(f"  femoral distal R : {R:.2f} mm sagittal, {fem_cor:.2f} mm coronal")
    print(f"  medial  sagittal : R {med_sag:7.2f} mm -> conformity {ratio(med_sag)}")
    print(f"  lateral sagittal : R {lat_sag:7.2f} mm -> conformity {ratio(lat_sag)}")
    if med_cor:
        print(f"  medial  coronal  : R {med_cor:7.2f} mm -> conformity "
              f"{fem_cor/med_cor:.2f}")
    if lat_cor:
        print(f"  lateral coronal  : R {lat_cor:7.2f} mm -> conformity "
              f"{fem_cor/lat_cor:.2f}")
    print()
    print(f"  socket floors    : medial y={my:+.1f}, lateral y={ly:+.1f}")
    print(f"  medial dish rise : {dish_rise(xs, ys, h, g.x_cond, my, 10.0):.2f} mm "
          f"10 mm posterior of the floor")
    print(f"  lateral dish rise: {dish_rise(xs, ys, h, -g.x_cond, ly, 10.0):.2f} mm "
          f"10 mm posterior of the floor")
    print(f"  medial  flat run : {flat_length(xs, ys, h, g.x_cond, my):5.1f} mm "
          f"within 0.25 mm of the floor")
    print(f"  lateral flat run : {flat_length(xs, ys, h, -g.x_cond, ly):5.1f} mm "
          f"within 0.25 mm of the floor")
    print(f"  anteromedial lip : {med_lip:.2f} mm above the medial floor")
    print(f"  posterolat. wall : {lat_wall:.2f} mm above the lateral floor")
    print(f"  eminence         : {eminence:.2f} mm above the medial floor")
    print()
    print(f"  pivot tracking to: {tracking:.0f} deg flexion before the femoral "
          f"lifts 1 mm off a fixed pivot")
    print(f"  medial contact   : drifts {mhi-mlo:.1f} mm A/P over 0-{tracking:.0f} "
          f"deg (a pivot, so this should stay small)")
    print(f"  lateral contact  : travels {lhi-llo:.1f} mm A/P over 0-{tracking:.0f} "
          f"deg, in a channel relieved for "
          f"{LATERAL_TRAVEL_ANT + LATERAL_TRAVEL_POST:.0f} mm")
    print(f"  min gap in sweep : {gap:+.3f} mm  (closest near {gap_at:.0f} deg; "
          f"must be >= 0)")
    print()
    print(f"  volume           : {volume/1000:.2f} cm3")
    print(f"  watertight       : {check_watertight(faces)}")
    print(f"  file size        : {out.stat().st_size/1e6:.2f} MB")


if __name__ == "__main__":
    main()
